name: Build and push image to ECR

on: 
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  ECR_URL: ${{ vars.ECR_URL_PYTHUMBNAILSCAPSTONE }}

jobs:

  Build_and_push_image:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4

        - uses: cschleiden/replace-tokens@v1
          with:
            files: '["**/.env"]'
          env:
            ENDPOINT: ${{ vars.RDS_ENDPOINT_ADDRESS }}
            DBUSER: ${{ secrets.DB_USERNAME }}
            DBPASS: ${{ secrets.DB_PASSWORD }}
            DBNAME: ${{ vars.RDS_DBNAME }}

        - name: Set variables (1)
          run: |
            full_url=$ECR_URL
            url_split=(${full_url//./ })
            echo "REGION=${url_split[3]}" >> "$GITHUB_ENV"
            url_split=(${full_url//// })
            echo "URL_ROOT=${url_split[0]}" >> "$GITHUB_ENV"
            echo "PROJ_NAME=${url_split[1]}" >> "$GITHUB_ENV"
            echo "VERSION=0.${{ github.run_number }}.0" >> "$GITHUB_ENV"

        - name: Set variables (2)
          run: |
            echo "NAME_AND_VERSION_TAG=$URL_ROOT/$PROJ_NAME:$VERSION" >> "$GITHUB_ENV"
            echo "NAME_AND_LATEST_TAG=$URL_ROOT/$PROJ_NAME:latest" >> "$GITHUB_ENV"

        - name: Show variables
          run: |
            echo $REGION
            echo $PROJ_NAME
            echo $URL_ROOT
            echo $VERSION
            echo $NAME_AND_VERSION_TAG
            echo $NAME_AND_LATEST_TAG

        - name: Connect with ECR
          run: |
            aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_URL

        - name: Build image
          run: |
            docker build -t $NAME_AND_VERSION_TAG .

        - name: Add latest tag
          run: |
            docker tag $NAME_AND_VERSION_TAG $NAME_AND_LATEST_TAG
            docker image ls

        - name: Push image to ECR
          run : | 
            docker push $NAME_AND_LATEST_TAG
            docker push $NAME_AND_VERSION_TAG

        - name: Update container image tag to use in ECS
          run: |
            curl -L -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $ACCESS_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/orgs/friends-ce-3-group/actions/variables/PYTHUMBNAILSCAPSTONE_IMAGE_VER_LATEST -d '{"name":"PYTHUMBNAILSCAPSTONE_IMAGE_VER_LATEST","value":"'$NAME_AND_VERSION_TAG'","visibility":"all"}'

        #- name: Trigger ECS to pull new image
        #  uses: convictional/trigger-workflow-and-wait@v1.6.1
        #  with:
        #    owner: friends-ce-3-group
        #    repo: capstone-ecs 
        #    workflow_file_name: update_infra.yml
        #    github_token: ${{ secrets.ACCESS_TOKEN }}
        #    ref: main
        #    wait_interval: 10
        #    trigger_workflow: true
        #    wait_workflow: true